### ISSUE TITLE
Any idea on build failure ?

### ISSUE THREAD

**Issue by luffah** [tube42/drumon#27]
I followed instruction in README, install java and android-sdk.

The issue i think is that there is no version precisions.
I installed openjdk-11 (11.0.7+10-2ubuntu) and android-sdk (25.0.0+10~18.0 ubuntu).

Then i tried to install / run the app and got this stacktrace.
Any idea ?

```shell
▓█ ./gradlew desktop:run
Downloading https://services.gradle.org/distributions/gradle-4.10.3-all.zip

Exception in thread "main" javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:214)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1967)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1924)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1907)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1423)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1400)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:104)
	at sun.security.validator.Validator.getInstance(Validator.java:181)
	at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:318)
	at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:179)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:193)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1670)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:226)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1082)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:1010)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1079)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1388)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1416)
	... 14 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
	at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
	at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:102)
	... 26 more

```

Too, as i install gradle, i tried to simple run `gradle` and got that stack:
```
A problem occurred configuring root project 'drumon'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.2.0.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:3.2.0.
         > Could not get resource 'https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/3.2.0/gradle-3.2.0.pom'.
            > org.apache.http.ssl.SSLInitializationException: /usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts (Aucun fichier ou dossier de ce type)
      > Could not resolve com.android.tools.build:gradle:3.2.0.
         > Could not get resource 'https://oss.sonatype.org/content/repositories/snapshots/com/android/tools/build/gradle/3.2.0/gradle-3.2.0.pom'.
            > org.apache.http.ssl.SSLInitializationException: /usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts (Aucun fichier ou dossier de ce type)
      > Could not resolve com.android.tools.build:gradle:3.2.0.
         > Could not get resource 'https://oss.sonatype.org/content/repositories/releases/com/android/tools/build/gradle/3.2.0/gradle-3.2.0.pom'.
            > org.apache.http.ssl.SSLInitializationException: /usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts (Aucun fichier ou dossier de ce type)
      > Could not resolve com.android.tools.build:gradle:3.2.0.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.2.0/gradle-3.2.0.pom'.
            > org.apache.http.ssl.SSLInitializationException: /usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts (Aucun fichier ou dossier de ce type)
      > Could not resolve com.android.tools.build:gradle:3.2.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.2.0/gradle-3.2.0.pom'.
            > org.apache.http.ssl.SSLInitializationException: /usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts (Aucun fichier ou dossier de ce type)
```

**Comment by tube42** [comment]
This is probably Google not supporting newer JDKs.

If you are building from source to test the contrast issue, v0.3.3 is already on f-droid.

**Comment by luffah** [comment]
i got the same issue with openjdk-8
